Algoritmo "Fahrenheit"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : [Conversor de graus Farenheit em Celsius]
// Autor(a)    : Eduardo Santos
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis
f: real
c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite a temperatura em Fº: ")
leia(f)
c<-((f-32)*5/9)
Escreval("Temperatura em Celsius é: ",c,"°")

Fimalgoritmo